### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by Cat-Lover-Yes** [WU-CVGL/BAD-NeRFstudio#1]
安装你们的bad-berf后，会影响原有的nerfstudio组件工作，当我在使用ns-export poisson命令时出现错误，其中错误显示如下
Traceback (most recent call last) ────────────────────────────────╮
│ /home/ydf/anaconda3/envs/nerfstudio/bin/ns-export:5 in <module>                                  │
│                                                                                                  │
│   2 # -*- coding: utf-8 -*-                                                                      │
│   3 import re                                                                                    │
│   4 import sys                                                                                   │
│ ❱ 5 from nerfstudio.scripts.exporter import entrypoint                                           │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│   8 │   sys.exit(entrypoint())                                                                   │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/scripts/exporter.py:48 in <module>                               │
│                                                                                                  │
│    45 )                                                                                          │
│    46 from nerfstudio.fields.sdf_field import SDFField                                           │
│    47 from nerfstudio.pipelines.base_pipeline import Pipeline, VanillaPipeline                   │
│ ❱  48 from nerfstudio.utils.eval_utils import eval_setup                                         │
│    49 from nerfstudio.utils.rich_utils import CONSOLE                                            │
│    50                                                                                            │
│    51                                                                                            │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/utils/eval_utils.py:28 in <module>                               │
│                                                                                                  │
│    25 import torch                                                                               │
│    26 import yaml                                                                                │
│    27                                                                                            │
│ ❱  28 from nerfstudio.configs.method_configs import all_methods                                  │
│    29 from nerfstudio.data.datamanagers.base_datamanager import VanillaDataManagerConfig         │
│    30 from nerfstudio.engine.trainer import TrainerConfig                                        │
│    31 from nerfstudio.pipelines.base_pipeline import Pipeline                                    │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/configs/method_configs.py:650 in <module>                        │
│                                                                                                  │
│   647                                                                                            │
│   648 all_methods, all_descriptions = method_configs, descriptions                               │
│   649 # Add discovered external methods                                                          │
│ ❱ 650 all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_m   │
│   651 all_methods, all_descriptions = sort_methods(all_methods, all_descriptions)                │
│   652                                                                                            │
│   653 # Register all possible external methods which can be installed with Nerfstudio            │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/plugins/registry.py:43 in discover_methods                       │
│                                                                                                  │
│   40 │   descriptions = {}                                                                       │
│   41 │   discovered_entry_points = entry_points(group="nerfstudio.method_configs")               │
│   42 │   for name in discovered_entry_points.names:                                              │
│ ❱ 43 │   │   spec = discovered_entry_points[name].load()                                         │
│   44 │   │   if not isinstance(spec, MethodSpecification):                                       │
│   45 │   │   │   CONSOLE.print(                                                                  │
│   46 │   │   │   │   f"[bold yellow]Warning: Could not entry point {spec} as it is not an ins    │
│                                                                                                  │
│ /home/ydf/anaconda3/envs/nerfstudio/lib/python3.9/site-packages/setuptools/_vendor/importlib_met │
│ adata/__init__.py:208 in load                                                                    │
│                                                                                                  │
│   205 │   │   return the named object.                                                           │
│   206 │   │   """                                                                                │
│   207 │   │   match = self.pattern.match(self.value)                                             │
│ ❱ 208 │   │   module = import_module(match.group('module'))                                      │
│   209 │   │   attrs = filter(None, (match.group('attr') or '').split('.'))                       │
│   210 │   │   return functools.reduce(getattr, attrs, module)                                    │
│   211                                                                                            │
│                                                                                                  │
│ /home/ydf/anaconda3/envs/nerfstudio/lib/python3.9/importlib/__init__.py:127 in import_module     │
│                                                                                                  │
│   124 │   │   │   if character != '.':                                                           │
│   125 │   │   │   │   break                                                                      │
│   126 │   │   │   level += 1                                                                     │
│ ❱ 127 │   return _bootstrap._gcd_import(name[level:], package, level)                            │
│   128                                                                                            │
│   129                                                                                            │
│   130 _RELOADING = {}                                                                            │
│                                                                                                  │
│ /home/ydf/nerfstudio/extand/BAD-NeRFstudio/badnerf/badnerf_config.py:14 in <module>              │
│                                                                                                  │
│   11 from badnerf.data.badnerf_datamanager import BadNerfDataManagerConfig                       │
│   12 from badnerf.data.badnerf_dataparser import BadNerfDataParserConfig                         │
│   13 from badnerf.engine.badnerf_vanilla_trainer import BadNerfVanillaTrainerConfig              │
│ ❱ 14 from badnerf.models.badnerfacto import BadNerfactoModelConfig                               │
│   15 from badnerf.pipelines.badnerf_vanilla_pipeline import BadNerfVanillaPipelineConfig         │
│   16                                                                                             │
│   17 badnerf_nerfacto = MethodSpecification(                                                     │
│                                                                                                  │
│ /home/ydf/nerfstudio/extand/BAD-NeRFstudio/badnerf/models/badnerfacto.py:28 in <module>          │
│                                                                                                  │
│    25                                                                                            │
│    26                                                                                            │
│    27 @dataclass                                                                                 │
│ ❱  28 class BadNerfactoModelConfig(NerfactoModelConfig):                                         │
│    29 │   """BAD-NeRF-nerfacto Model Config"""                                                   │
│    30 │                                                                                          │
│    31 │   _target: Type = field(                                                                 │
│                                                                                                  │
│ /home/ydf/anaconda3/envs/nerfstudio/lib/python3.9/dataclasses.py:1021 in dataclass               │
│                                                                                                  │
│   1018 │   │   return wrap                                                                       │
│   1019 │                                                                                         │
│   1020 │   # We're called as @dataclass without parens.                                          │
│ ❱ 1021 │   return wrap(cls)                                                                      │
│   1022                                                                                           │
│   1023                                                                                           │
│   1024 def fields(class_or_instance):                                                            │
│                                                                                                  │
│ /home/ydf/anaconda3/envs/nerfstudio/lib/python3.9/dataclasses.py:1013 in wrap                    │
│                                                                                                  │
│   1010 │   """                                                                                   │
│   1011 │                                                                                         │
│   1012 │   def wrap(cls):                                                                        │
│ ❱ 1013 │   │   return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)            │
│   1014 │                                                                                         │
│   1015 │   # See if we're being called as @dataclass or @dataclass().                            │
│   1016 │   if cls is None:                                                                       │
│                                                                                                  │
│ /home/ydf/anaconda3/envs/nerfstudio/lib/python3.9/dataclasses.py:927 in _process_class           │
│                                                                                                  │
│    924 │   │   flds = [f for f in fields.values()                                                │
│    925 │   │   │   │   if f._field_type in (_FIELD, _FIELD_INITVAR)]                             │
│    926 │   │   _set_new_attribute(cls, '__init__',                                               │
│ ❱  927 │   │   │   │   │   │      _init_fn(flds,                                                 │
│    928 │   │   │   │   │   │   │   │   │   frozen,                                               │
│    929 │   │   │   │   │   │   │   │   │   has_post_init,                                        │
│    930 │   │   │   │   │   │   │   │   │   # The name to use for the "self"                      │
│                                                                                                  │
│ /home/ydf/anaconda3/envs/nerfstudio/lib/python3.9/dataclasses.py:504 in _init_fn                 │
│                                                                                                  │
│    501 │   │   │   if not (f.default is MISSING and f.default_factory is MISSING):               │
│    502 │   │   │   │   seen_default = True                                                       │
│    503 │   │   │   elif seen_default:                                                            │
│ ❱  504 │   │   │   │   raise TypeError(f'non-default argument {f.name!r} '                       │
│    505 │   │   │   │   │   │   │   │   'follows default argument')                               │
│    506 │                                                                                         │
│    507 │   locals = {f'_type_{f.name}': f.type for f in fields}                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: non-default argument 'camera_optimizer' follows default argument

**Comment by LingzheZhao** [comment]
你好，我们之前没有测试过nerfstudio导出mesh的这个功能，我调试了一下，现在应该可以了，你可以看一下这个PR能不能解决你的问题：https://github.com/WU-CVGL/BAD-NeRFstudio/pull/2
我这边测试是OK的：

```bash
ns-export poisson --load-config outputs/blurtanabata/bad-nerfacto/2023-10-11_234009/config.yml --output-dir exports --normal-method open3d
```

![image](https://github.com/WU-CVGL/BAD-NeRFstudio/assets/43722188/012cfabf-4761-4b72-a6b8-40cb225d2339)
