### ISSUE TITLE
训练错误

### ISSUE THREAD

**Issue by Cat-Lover-Yes** [WU-CVGL/BAD-NeRFstudio#4]
当我使用以下命令训练模型时，会出现接下来的错误
ns-train bad-nerfacto --pipeline.model.predict-normals True --vis tensorboard --output-dir <path> --data <path>

**Comment by Cat-Lover-Yes** [comment]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ydf/anaconda3/envs/nerfstudio/bin/ns-train:8 in <module>                                   │
│                                                                                                  │
│   5 from nerfstudio.scripts.train import entrypoint                                              │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(entrypoint())                                                                   │
│   9                                                                                              │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/scripts/train.py:261 in entrypoint                               │
│                                                                                                  │
│   258 │   """Entrypoint for use with pyproject scripts."""                                       │
│   259 │   # Choose a base configuration and override values.                                     │
│   260 │   tyro.extras.set_accent_color("bright_yellow")                                          │
│ ❱ 261 │   main(                                                                                  │
│   262 │   │   tyro.cli(                                                                          │
│   263 │   │   │   AnnotatedBaseConfigUnion,                                                      │
│   264 │   │   │   description=convert_markup_to_ansi(__doc__),                                   │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/scripts/train.py:246 in main                                     │
│                                                                                                  │
│   243 │   config.print_to_terminal()                                                             │
│   244 │   config.save_config()                                                                   │
│   245 │                                                                                          │
│ ❱ 246 │   launch(                                                                                │
│   247 │   │   main_func=train_loop,                                                              │
│   248 │   │   num_devices_per_machine=config.machine.num_devices,                                │
│   249 │   │   device_type=config.machine.device_type,                                            │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/scripts/train.py:189 in launch                                   │
│                                                                                                  │
│   186 │   elif world_size == 1:                                                                  │
│   187 │   │   # uses one process                                                                 │
│   188 │   │   try:                                                                               │
│ ❱ 189 │   │   │   main_func(local_rank=0, world_size=world_size, config=config)                  │
│   190 │   │   except KeyboardInterrupt:                                                          │
│   191 │   │   │   # print the stack trace                                                        │
│   192 │   │   │   CONSOLE.print(traceback.format_exc())                                          │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/scripts/train.py:100 in train_loop                               │
│                                                                                                  │
│    97 │   _set_random_seed(config.machine.seed + global_rank)                                    │
│    98 │   trainer = config.setup(local_rank=local_rank, world_size=world_size)                   │
│    99 │   trainer.setup()                                                                        │
│ ❱ 100 │   trainer.train()                                                                        │
│   101                                                                                            │
│   102                                                                                            │
│   103 def _distributed_worker(                                                                   │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/engine/trainer.py:255 in train                                   │
│                                                                                                  │
│   252 │   │   │   │   │   │   │   )                                                              │
│   253 │   │   │   │   │   │                                                                      │
│   254 │   │   │   │   │   │   # time the forward pass                                            │
│ ❱ 255 │   │   │   │   │   │   loss, loss_dict, metrics_dict = self.train_iteration(step)         │
│   256 │   │   │   │   │   │                                                                      │
│   257 │   │   │   │   │   │   # training callbacks after the training iteration                  │
│   258 │   │   │   │   │   │   for callback in self.callbacks:                                    │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/utils/profiler.py:127 in inner                                   │
│                                                                                                  │
│   124 │   │   def inner(*args, **kwargs):                                                        │
│   125 │   │   │   self._function_call_args = (args, kwargs)                                      │
│   126 │   │   │   with self:                                                                     │
│ ❱ 127 │   │   │   │   out = func(*args, **kwargs)                                                │
│   128 │   │   │   self._function_call_args = None                                                │
│   129 │   │   │   return out                                                                     │
│   130                                                                                            │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/engine/trainer.py:468 in train_iteration                         │
│                                                                                                  │
│   465 │   │   ), f"gradient_accumulation_steps must be > 0, not {self.gradient_accumulation_st   │
│   466 │   │   for _ in range(self.gradient_accumulation_steps):                                  │
│   467 │   │   │   with torch.autocast(device_type=cpu_or_cuda_str, enabled=self.mixed_precisio   │
│ ❱ 468 │   │   │   │   _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step   │
│   469 │   │   │   │   loss = functools.reduce(torch.add, loss_dict.values())                     │
│   470 │   │   │   │   loss /= self.gradient_accumulation_steps                                   │
│   471 │   │   │   self.grad_scaler.scale(loss).backward()  # type: ignore                        │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/utils/profiler.py:127 in inner                                   │
│                                                                                                  │
│   124 │   │   def inner(*args, **kwargs):                                                        │
│   125 │   │   │   self._function_call_args = (args, kwargs)                                      │
│   126 │   │   │   with self:                                                                     │
│ ❱ 127 │   │   │   │   out = func(*args, **kwargs)                                                │
│   128 │   │   │   self._function_call_args = None                                                │
│   129 │   │   │   return out                                                                     │
│   130                                                                                            │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/pipelines/base_pipeline.py:281 in get_train_loss_dict            │
│                                                                                                  │
│   278 │   │   │   step: current iteration step to update sampler if using DDP (distributed)      │
│   279 │   │   """                                                                                │
│   280 │   │   ray_bundle, batch = self.datamanager.next_train(step)                              │
│ ❱ 281 │   │   model_outputs = self._model(ray_bundle)  # train distributed data parallel model   │
│   282 │   │   metrics_dict = self.model.get_metrics_dict(model_outputs, batch)                   │
│   283 │   │                                                                                      │
│   284 │   │   if self.config.datamanager.camera_optimizer is not None:                           │
│                                                                                                  │
│ /home/ydf/anaconda3/envs/nerfstudio/lib/python3.9/site-packages/torch/nn/modules/module.py:1501  │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /home/ydf/nerfstudio/nerfstudio/models/base_model.py:142 in forward                              │
│                                                                                                  │
│   139 │   │   if self.collider is not None:                                                      │
│   140 │   │   │   ray_bundle = self.collider(ray_bundle)                                         │
│   141 │   │                                                                                      │
│ ❱ 142 │   │   return self.get_outputs(ray_bundle)                                                │
│   143 │                                                                                          │
│   144 │   def get_metrics_dict(self, outputs, batch) -> Dict[str, torch.Tensor]:                 │
│   145 │   │   """Compute and returns metrics.                                                    │
│                                                                                                  │
│ /home/ydf/nerfstudio/extand/badnerfstudio/badnerf/models/badnerfacto.py:56 in get_outputs        │
│                                                                                                  │
│    53 │   def get_outputs(self, ray_bundle: RayBundle):                                          │
│    54 │   │   is_training = self.training and torch.is_grad_enabled()                            │
│    55 │   │   # apply the camera optimizer pose tweaks                                           │
│ ❱  56 │   │   ray_bundle = self.camera_optimizer.apply_to_raybundle(ray_bundle, is_training)     │
│    57 │   │   ray_samples: RaySamples                                                            │
│    58 │   │   ray_samples, weights_list, ray_samples_list = self.proposal_sampler(ray_bundle,    │
│    59 │   │   field_outputs = self.field.forward(ray_samples, compute_normals=self.config.pred   │
│                                                                                                  │
│ /home/ydf/anaconda3/envs/nerfstudio/lib/python3.9/site-packages/torch/nn/modules/module.py:1614  │
│ in __getattr__                                                                                   │
│                                                                                                  │
│   1611 │   │   │   modules = self.__dict__['_modules']                                           │
│   1612 │   │   │   if name in modules:                                                           │
│   1613 │   │   │   │   return modules[name]                                                      │
│ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
│   1615 │   │   │   type(self).__name__, name))                                                   │
│   1616 │                                                                                         │
│   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'BadNerfactoModel' object has no attribute 'camera_optimizer'

**Comment by Cat-Lover-Yes** [comment]
然而，我已经git pull了最新的主分支，具体的代码如下：
class BadNerfactoModel(NerfactoModel):
    """BAD-NeRF-nerfacto Model model

    Args:
        config: configuration to instantiate model
    """

    config: BadNerfactoModelConfig
    camera_optimizer: BadNerfCameraOptimizer
    
很显然存在这样的属性，所以这是为什么？是我的安装方式有问题吗？

**Comment by Cat-Lover-Yes** [comment]
我的nerfstudio是以源代码的形式安装的，所以，我在拉取你们的代码时，采用了以下方式：
path: ./nerfstudio/extand/badnerfstudio
在这个目录中，我用pip install -e .安装了代码，请问这和报错有关系吗？

**Comment by LingzheZhao** [comment]
我跑了一下，加上`--pipeline.model.predict-normals True`参数之后，我这边能够正常训练，没能复现你的报错... 想问下你的nerfstudio是最新的吗?可以在nerfstudio源码目录下，用`git show --oneline -s` 打印一下你的源码所在的commit的hash

**Comment by Cat-Lover-Yes** [comment]
> 我跑了一下，加上`--pipeline.model.predict-normals True`参数之后，我这边能够正常训练，没能复现你的报错... 想问下你的nerfstudio是最新的吗?可以在nerfstudio源码目录下，用`git show --oneline -s` 打印一下你的源码所在的commit的hash

aa51bc8 (HEAD -> main, origin/main, origin/HEAD) minor update README.md
我的版本如上

**Comment by Cat-Lover-Yes** [comment]
> 我跑了一下，加上`--pipeline.model.predict-normals True`参数之后，我这边能够正常训练，没能复现你的报错... 想问下你的nerfstudio是最新的吗?可以在nerfstudio源码目录下，用`git show --oneline -s` 打印一下你的源码所在的commit的hash

我的版本如下
d78af5b5 (HEAD -> main, origin/main, origin/HEAD) allow ns-process-data to use CR2 raw images (#2119)

**Comment by LingzheZhao** [comment]
嗯 应该是版本太老了，可以在nerfstudio源码目录下`git pull`更新一下，然后`pip install`安装最新的nerfstudio
